# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to use VariantBuilder properties to disable tests in a project
  """

[agpVersion]
min = "8.7.0-alpha08"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkDebugTestStatus",
    ":app:checkReleaseTestStatus"
]

# All the relevant metadata fields to create an index based on language/API/etc
[indexMetadata]
index = [
    "Call chains/androidComponents.beforeVariants {}",
    "Call chains/androidComponents.onVariants {}",
    "APIs/AndroidComponentsExtension.beforeVariants()",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/HasHostTestsBuilder.hostTests.get().enable",
    "Call chains/HasDeviceTestsBuilder.deviceTests.get().enable",
    "Call chains/HasHostTests.hostTests.get()",
    "Call chains/HasDeviceTests.deviceTests.get()",
    "APIs/HasDeviceTestsBuilder.deviceTests",
    "APIs/HasDeviceTests.deviceTests",
    "APIs/HasHostTestsBuilder.hostTests",
    "APIs/HasHostTests.hostTests",
    "HostTestBuilder.UNIT_TEST_TYPE",
    "DeviceTestBuilder.ANDROID_TEST_TYPE"
]
