# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to use the InAndOutDirectoryOperationRequest.toTransform() API on an object of type
  Artifact.Single and Artifact.Transformable
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkDebugAssets"
]

# All the relevant metadata fields to create an index based on language/API/etc
[indexMetadata]
index = [
    "Themes/Artifact API",
    "Call chains/variant.artifacts.get()",
    "Call chains/variant.artifacts.use().wiredWithDirectories().toTransform()",
    "Call chains/androidComponents.onVariants {}",
    "APIs/InAndOutDirectoryOperationRequest.toTransform()",
    "APIs/Artifacts.use()",
    "APIs/Artifacts.get()",
    "APIs/SingleArtifact.ASSETS",
    "APIs/Component.artifacts",
    "APIs/TaskBasedOperation.wiredWithDirectories()",
    "APIs/AndroidComponentsExtension.onVariants()"
]
