# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Customizing test dependencies with dependencySubstitution of variant API.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:assemble",
    ":app:testDebugUnitTest",
    ":app:testReleaseUnitTest",
    ":app:assembleAndroidTest"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Dependency Resolution",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/androidComponents.selector().withBuildType()",
    "APIs/VariantSelector.withBuildType()",
    "APIs/Variant.nestedComponents",
    "APIs/Variant.components",
    "APIs/Component.compileConfiguration",
    "APIs/Component.runtimeConfiguration",
    "APIs/Configuration.resolutionStrategy",
    "APIs/ResolutionStrategy.dependencySubstitution()",
    "Call chains/configuration.resolutionStrategy.dependencySubstitution {}",
    "Call chains/substitute().using()",
]
