# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to transform classes that will be used to create the dex files.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:assembleDebug"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.forScope().use().toTransform()",
    "APIs/Artifacts.forScope()",
    "APIs/ScopedArtifacts.use()",
    "APIs/ScopedArtifactsOperation.toTransform()",
    "APIs/ScopedArtifact.CLASSES",
    "APIs/ScopedArtifacts.Scope.PROJECT",
]
