# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that listens to the creation of the APK to copy it somewhere else
  """

[agpVersion]
min = "8.3.0-beta01"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "assembleDebug",
]
validationTasks = [
    "validateDebug"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.use().wiredWith().toListenTo()",
    "APIs/Artifacts.use()",
    "APIs/TaskBasedOperation.wiredWith()",
    "APIs/OutOperationRequest.toListenTo()",
    "APIs/SingleArtifact.APK",
    "APIs/BuiltArtifact.versionCode",
    "APIs/BuiltArtifact.versionName",
    "APIs/BuiltArtifacts.elements",
    "APIs/BuiltArtifacts.variantName",
    "APIs/BuiltArtifactsLoader.load()",
    "APIs/Artifact.ContainsMany",
    "Renaming APKs"
]
