# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe to add some custom asset from a Task.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "debugVerifyAsset"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Android Assets",
    "Themes/Sources",
    "APIs/SourceDirectories.addGeneratedSourceDirectory()",
    "APIs/SingleArtifact.ASSETS",
    "APIs/Artifacts.get()",
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/Component.artifacts",
    "APIs/Component.sources",
    "Call chains/variant.sources.*.addGeneratedSourceDirectory()",
    "Call chains/variant.artifacts.get()",
    "Call chains/androidComponents.onVariants {}"
]
