# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to update Android manifest in a meaningful way.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:debugManifestUpdater",
    ":app:gitVersionProvider",
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Android Manifest",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.use().wiredWithFiles().toTransform()",
    "APIs/Component.artifacts",
    "APIs/Artifacts.use()",
    "APIs/TaskBasedOperation.wiredWithFiles()",
    "APIs/InAndOutFileOperationRequest.toTransform()",
    "Call chains/task.outputs.upToDateWhen {}",
    "APIs/TaskOutputs.upToDateWhen()",
    "APIs/task.getOutputs()",
    "APIs/SingleArtifact.MERGED_MANIFEST",
]

