# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to transform the artifact in async way
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:copyDebugApks"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.use().wiredWithDirectories().toTransformMany()",
    "APIs/Artifacts.use()",
    "APIs/TaskBasedOperation.wiredWithDirectories()",
    "APIs/InAndOutDirectoryOperationRequest.toTransformMany()",
    "APIs/SingleArtifact.APK",
    "APIs/ArtifactTransformationRequest",
    "Call chains/transformationRequest.submit()",
    "APIs/BuiltArtifact"
]

