# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that appends a generated directory to an instance of MultipleArtifact.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugBundle"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "onVariant",
    "variant.artifacts.use",
    "variant.artifacts.get",
    "MultipleArtifact",
    "MultipleArtifact.NATIVE_DEBUG_METADATA",
    "OutOperationRequest.toAppendTo()",
    "SingleArtifact.BUNDLE",
]

