# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that creates a single artifact (android manifest file).
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:verifyDebugManifest",
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "Themes/Android Manifest",
    "Call chains/androidComponents.onVariants {}",
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/SingleArtifact.MERGED_MANIFEST",
    "APIs/Artifacts.use()",
    "APIs/OutOperationRequest.toCreate()",
    "APIs/TaskBasedOperation.wiredWith()",
    "Call chains/variant.artifacts.use().wiredWith().toCreate()",
    "APIs/Component.artifacts",
    "APIs/TaskProvider.flatMap()"
]
