# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  allProjectsAction recipe show how to iterate over all projects and recover produced APKs for each of them.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
  "allProjectsAction",
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
  "settings plugin",
  "onVariant",
  "All projects",
  "SingleArtifact.APK",
  "variant.artifacts.get",
]
