# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
   This sample shows how to select multiple variants by using selector() in Variant API.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkFullMinApi24ReleaseConfiguration",
    ":app:checkDemoMinApi21DebugConfiguration",
    ":app:checkDemoMinApi24DebugConfiguration",
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "APIs/AndroidComponentsExtension.beforeVariants()",
    "Call chains/androidComponents.beforeVariants {}",
    "APIs/AndroidComponentsExtension.selector()",
    "APIs/VariantSelector.withFlavor()",
    "Call chains/androidComponents.selector().withFlavor()",
    "APIs/VariantSelector.withBuildType()",
    "Call chains/androidComponents.selector().withBuildType()",
    "APIs/VariantSelector.withName()",
    "Call chains/androidComponents.selector().withName()",
    "APIs/VariantSelector.all()",
    "Call chains/androidComponents.selector().all()",
    "APIs/VariantBuilder.minSdk",
    "APIs/CanMinifyAndroidResourcesBuilder.shrinkResources",
    "APIs/CanMinifyCodeBuilder.isMinifyEnabled",
    "APIs/HasUnitTestBuilder.enableUnitTest",
]
