# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Template recipe
  """

[agpVersion]
min = "8.2.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "debugTemplateRecipe",
    "releaseTemplateRecipe"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
]
