# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that adds a static directory to an instance of MultipleArtifact.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugBundle"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "Call chains/androidComponents.onVariants {}",
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/Component.artifacts",
    "APIs/Artifacts.get()",
    "APIs/Artifacts.add()",
    "Call chains/variant.artifacts.add()",
    "Call chains/variant.artifacts.get()",
    "APIs/MultipleArtifact.NATIVE_DEBUG_METADATA",
    "APIs/SingleArtifact.BUNDLE",
]

