# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to register a task dependency on the PreBuild lifecycle task.
  """

[agpVersion]
min = "8.4.0-alpha13"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "assembleDebug"
]
validationTasks = [
    "validateDebug"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.registerPreBuild()",
    "APIs/LifeCycleTasks.registerPreBuild()"
]
