# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that gets a single artifact (the app bundle) and verifies it in a task.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugBundle"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "onVariant",
    "variant.artifacts.get",
    "SingleArtifact.BUNDLE",
]
