# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that adds a task per variant to consume an instance of MultipleArtifact.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugMultiDexKeepProguardFiles"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "Call chains/androidComponents.onVariants {}",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/variant.artifacts.getAll()",
    "APIs/Component.artifacts",
    "APIs/Artifacts.getAll()",
    "APIs/MultipleArtifact.MULTIDEX_KEEP_PROGUARD",
]
