# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  perVariantManifestPlaceholder recipe
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
  "debugManifestVerifier",
  "releaseManifestVerifier"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Android Manifest",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.manifestPlaceholders.put()",
    "APIs/Variant.manifestPlaceholders",
    "APIs/MapProperty.put()",
    "Placeholders",
    "APIs/SingleArtifact.MERGED_MANIFEST",
    "APIs/Artifacts.get()",
    "Call chains/variant.artifacts.get()"
]
