# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  Recipe that appends to a scoped artifact and verifies in a task.
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugClasses"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/Artifact API",
    "APIs/AndroidComponentsExtension.onVariants()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.artifacts.forScope().use().toAppend()",
    "APIs/Component.artifacts",
    "APIs/Artifacts.forScope()",
    "APIs/ScopedArtifacts.Scope.ALL",
    "APIs/ScopedArtifacts.Scope.PROJECT",
    "APIs/ScopedArtifacts.use()",
    "APIs/ScopedArtifact.CLASSES",
    "APIs/ScopedArtifactsOperation.toGet()",
    "APIs/ScopedArtifactsOperation.toAppend()"
]
