# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to use the Instrumentation.transformClassesWith() API on a project
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkDebugAsmTransformation"
]

# All the relevant metadata fields to create an index based on language/API/etc
[indexMetadata]
index = [
    "Call chains/variant.artifacts.get()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/variant.instrumentation.transformClassesWith()",
    "APIs/Instrumentation.transformClassesWith()",
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/ScopedArtifact.CLASSES",
    "APIs/ScopedArtifacts.Scope.PROJECT",
    "APIs/ScopedArtifacts.use()",
    "APIs/ScopedArtifactsOperation.toGet()",
    "Call chains/variant.artifacts.forScope().use().toGet()"
]
