# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This sample shows how to use the CombiningOperationRequest.toTransform() API on an object of type Artifact.Multiple
  and Artifact.Transformable
  """

[agpVersion]
min = "8.4.0-alpha10"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkDebugNativeDebugMetadata"
]

# All the relevant metadata fields to create an index based on language/API/etc
[indexMetadata]
index = [
    "Themes/Artifact API",
    "Call chains/variant.artifacts.add()",
    "Call chains/variant.artifacts.get()",
    "Call chains/variant.artifacts.use().wiredWith().toTransform()",
    "Call chains/androidComponents.onVariants {}",
    "APIs/CombiningOperationRequest.toTransform()",
    "APIs/Artifacts.add()",
    "APIs/Artifacts.use()",
    "APIs/Artifacts.get()",
    "APIs/MultipleArtifact.NATIVE_DEBUG_METADATA",
    "APIs/Component.artifacts",
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/TaskBasedOperation.wiredWith()"
]
