# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This recipe shows how to add a new custom source folders to the Variant
  """

[agpVersion]
min = "8.1.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "sourceSets",
    "debugDisplayAllSources",
    "debugAddCustomSources"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "onVariant",
    "registerSourceType",
    "addStaticSourceDirectory",
    "addGeneratedSourceDirectory",
    "SourceDirectories.add",
]
